### ISSUE TITLE
ETA on macOS support

### ISSUE THREAD

**Issue by morajabi** [FabianLars/tauri-plugin-deep-link#10]
Thank you for your work here! Is there any roadmap/plan available on when can we expect macOS support? Or let us know how can we help, please.

**Comment by thejawker** [comment]
Hi @FabianLars! Thanks so much for Tauri, it's been so much fun to work with! I was curious to the status of this or if there are ways around it.

**Comment by FabianLars** [comment]
@thejawker Thank you :) Unfortunately, my last comment is still accurate. I tried to hack it together with the fruitbasket crate and obj-c but wasn't able to make either one work which is probably caused by my lacking macos experience 🤷

**Comment by thejawker** [comment]
All good, thanks for the response @FabianLars! I'll poke around a bit myself. Appreciate the project!

**Comment by dukeeagle** [comment]
Hey everyone! Does anyone know the latest status of this?

**Comment by FabianLars** [comment]
Unless there is a community member working on it in the shadows my 1 month old comment above is still accurate.

I _feel_ like i'm getting closer to a solution but it's still crashing all the time so probably just wishful thinking 😂 (i don't work on it regularly btw, just when i don't have anything better to do, which was quite rare the last few months)

**Comment by FabianLars** [comment]
i think i finally found something that seems to work. I'll upload a testing branch in the next few days, i'd appreciate it if a few people could test it then :heart:
