### ISSUE TITLE
The listeners do not get invoked when primary instance was started by the uri scheme

### ISSUE THREAD

**Issue by joshua7v** [FabianLars/tauri-plugin-deep-link#29]
I'm using the code from the example,
when app gets started by uri scheme, the event listener does not receive anything.

Is it possible that the js side does not get ready before event emition?
I don't know much of rust, its just my dumb guess.

```rust
tauri_plugin_deep_link::prepare("...");

tauri::Builder::default()
    .setup(|app| {
        let window = app.get_window("main").unwrap();
        set_shadow(&window, true).expect("unsupported platform");

        let handle = app.handle();
        tauri_plugin_deep_link::register("example", move |request| {
            dbg!(&request);
            handle.emit_all("scheme-request-received", request).unwrap();
        })
        .unwrap();

        if let Some(url) = std::env::args().nth(1) {
            app.emit_all("scheme-request-received", url).unwrap();
        }

        Ok(())
    })
    .plugin(tauri_plugin_window_state::Builder::default().build())
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
```

```typescript
listen('scheme-request-received', async ({ event, payload }) => {
  console.log(event, payload);
});
```

**Comment by FabianLars** [comment]
> Is it possible that the js side does not get ready before event emition?

That is absolutely correct and i thought i added a note about it in the example but apparently i didn't...

The easiest solution if you don't know Rust is to do something like this
```rs
        if let Some(url) = std::env::args().nth(1) {
            let _ = window.eval(format!("window.urlSchemeRequest='{}'", url));
        }
```
Then you can check for `window.urlSchemeRequst` in your frontend.

I will try to think about a nicer api in the future, but no promises.

**Comment by joshua7v** [comment]
Great. I managed to achieve what I want with your help. Thanks.

**Comment by cameronvoell** [comment]
@joshua7v I am running into the same issue, do you mind sharing how you communicated to Front end when your primary instance was launched by the URL scheme? Thanks 🙇

**Comment by joshua7v** [comment]
> @joshua7v I am running into the same issue, do you mind sharing how you communicated to Front end when your primary instance was launched by the URL scheme? Thanks 🙇

@cameronvoell well, I literally just followed the advice given by FabianLars,
the intention behind that is you could attach something on the window object from rust,
and then pick it up in the app when the app gets started.

Since the app is not ready by the time, you have to save it somewhere(on the window object would be an option)

**Comment by r3wt** [comment]
Fabian's code above didn't work for me, but from google i found the `stringify!` macro and then cast to `str` for window.eval, which works:
```rs
if let Some(url) = std::env::args().nth(1) {
  let _ = window.eval(format!(stringify!("window.urlSchemeRequest='{}'"), url).as_str());
}
```
