### ISSUE TITLE
tauri-plugin-deep-link  Parameter acquisition problem

### ISSUE THREAD

**Issue by HQ222222** [FabianLars/tauri-plugin-deep-link#32]
Hello, I am a user of your work. I am very sorry to bother you, but I have some problems when using the plug-in. I need to get "myapp://message? "phone=xxx" is triggered with parameters, if possible, I need some guidance from you,very thankful！ here is my code
My environment：tauri1.4.0, windows 11

    tauri::Builder::default()
        .setup(|app| {
            let handle = app.handle();
         
            tauri_plugin_deep_link::register("myapp", move |request| {
                dbg!(&request);
                // ❗ I didn't get the passed parameter on the first wake up, and only when the app was already open did I use "myapp://message? "again. phone=xxx" to successfully obtain parameters
                handle.emit_all("test", request).unwrap();
            })
            .unwrap();
            #[cfg(not(target_os = "macos"))]
            if let Some(url) = std::env::args().nth(1) {
                app.emit_all("test", url).unwrap();
            }
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while running myapp application")
        .run(|_app_handle, event| match event {
            tauri::RunEvent::ExitRequested { api, .. } => {
              api.prevent_exit();
            }
            _ => {}
          });

**Comment by FabianLars** [comment]
Hi 👋 

The solution depends on your requirements / app flow. If your app is started via the deep link the emit_all call will likely get lost because your frontend isn't listening to that event yet at this point.

I'm thinking about adding a `get_last_url` api or something to not have to worry about timing as much 🤔

**Comment by HQ222222** [comment]
> Hi 👋
> 
> The solution depends on your requirements / app flow. If your app is started via the deep link the emit_all call will likely get lost because your frontend isn't listening to that event yet at this point.
> 
> I'm thinking about adding a `get_last_url` api or something to not have to worry about timing as much 🤔

Yes, I did consider it, because the web front end hadn't started listening when emit_all was triggered, so I tried to save the content in a local file when it was triggered, and then read the content in the run() method and re-emit_all, but I didn't succeed. I am trying other schemes to achieve the same effect. Thank you very much for your reply
