### ISSUE TITLE
MacOS: No url received for primary window instance

### ISSUE THREAD

**Issue by tarushnagpal** [FabianLars/tauri-plugin-deep-link#35]
When the app is closed and is being opened for the first time with a url such as `scheme://some/path`, the newly opened window does not get the path value from the scheme request

**Comment by FabianLars** [comment]
Hi 👋 

Could you post the output of the `tauri info` command please?

And a bit of your code too (at least everything that uses this plugin but preferebly more so i can see the context). Right now i'd assume it's something specific to your code since it works for me and others afaik :)

**Comment by FabianLars** [comment]
Ah actually, it may also be a timing issue if you only try to read it in javascript with an event listener. When the app is starting and immediatly emitting the event your js won't have had the chance to register the listener yet.

**Comment by tarushnagpal** [comment]
> And a bit of your code too (at least everything that uses this plugin but preferebly more so i can see the context). Right now i'd assume it's something specific to your code since it works for me and others afaik :)
It's the same as the example in this repo

> Ah actually, it may also be a timing issue if you only try to read it in javascript with an event listener. When the app is starting and immediatly emitting the event your js won't have had the chance to register the listener yet.

That's exactly what I came to too, is there a way to know when the webview has been loaded in tauri? Maybe we can queue our scheme requests till the js is loaded?

**Comment by FabianLars** [comment]
> is there a way to know when the webview has been loaded in tauri?

Not really. Realistically the only way is to have your frontend send an event (or call a tauri command) when it's done. javascript is too "dynamic" (for the lack of a better word) that the webview can never know when it's actually ready.

**Comment by tarushnagpal** [comment]
Hmm okay then it would be an easy fix for the app to send a "Hey I have started listening" to rust and then I can just flush the queue for the url events here. Would you like me to add this change to the plugin itself? 

Maybe we can add requests to queue until we get the first `listen` call and then send them all?

**Comment by FabianLars** [comment]
The v1 plugin doesn't accept any new features (mainly because my personal account doesn't have access to the crates.io package anymore). At least not if those features could be implemented in apps directly somewhat easily, in this case the scheme(s) could be saved in tauri::State and accessed via a tauri command for example.

v2 (mobile only rn) already has an api getLastScheme or something that should work here.

> Maybe we can add requests to queue until we get the first listen call and then send them all?

iirc we once had a queue in tauri itself but it caused more problems than it solved.
