### ISSUE TITLE
Does deep-link v2 support linux, win, and mac?

### ISSUE THREAD

**Issue by HuntFeng** [FabianLars/tauri-plugin-deep-link#42]
This might be a silly question. I want to migrate my app to Tauri v2, and I noticed that deep-link v2 supports ios and andriod. 

Does deep-link v2 support desktop (linux, win, mac) or is it a feature in progress?

**Comment by FabianLars** [comment]
Hi, sorry for the delay. The v2 branch in this repo only forks for v2 alpha desktop-only projects, i would not recommend using it.
We've moved this plugin into the official repositories. If you only have to register the schemes on installation then tauri's cli/bundler already supports it. For runtime apis there's a PR [here](https://github.com/tauri-apps/plugins-workspace/pull/916) that i want to merge this week hopefully.

**Comment by HuntFeng** [comment]
Thanks for the info. Indeed I only need to register the urls at install time. 

Great work!
